### ISSUE TITLE
How are karl.views.admin.archive_communities_view and karl.box.apiviews.get_communities_to_archive related?

### ISSUE THREAD

**Issue by jimfulton** [karlproject/karl#157]
Is the former a decoy? (It has a testing comment that suggests it might be.)

**Comment by pauleveritt** [comment]
The former is hooked (I believe) into an ADMIN view that archives but not to Box. It isn't used any more, I believe.

**Comment by jimfulton** [comment]
It might be a good idea to remove it then. It's almost certainly not doing what was intended, given that it has a debugging line in it that changes the inactive cutoff to a few days.

**Comment by pauleveritt** [comment]
+1

**Comment by jimfulton** [comment]
OK, I'll get rid of it.

**Comment by jimfulton** [comment]
Maybe an aside: Calvin mentioned to me at PyCon that he uses KARL. Hopefully, this doesn't break them.
